/**
 * 全局事件名枚举
 */
export enum GameEvent {
    // 通用弹窗提示
    SHOW_TIPS = "SHOW_TIPS",

    // 经济金币
    GOLD_CHANGE = "GOLD_CHANGE",

    // 炮塔建造相关
    TOWER_BUILD_CLICK = "TOWER_BUILD_CLICK",
    TOWER_UPGRADE = "TOWER_UPGRADE",
    TOWER_SELL = "TOWER_SELL",
    TOWER_SELECT = "TOWER_SELECT",

    // 敌人&波次
    WAVE_START = "WAVE_START",
    WAVE_END = "WAVE_END",
    ENEMY_SPAWN = "ENEMY_SPAWN",
    ENEMY_DIE = "ENEMY_DIE",

    // 战斗流程
    BATTLE_START = "BATTLE_START",
    BATTLE_WIN = "BATTLE_WIN",
    BATTLE_LOSE = "BATTLE_LOSE",

    ENTITY_CREATE = "ENTITY_CREATE",//实体创建
    ENTITY_DESTROY = "ENTITY_DESTROY",//实体销毁
    ENTITY_STATE_CHANGE = "ENTITY_STATE_CHANGE",//实体状态改变
    ENTITY_ATTACK = "ENTITY_ATTACK ",//实体攻击,
    ENTITY_HP_UPDATE = "ENTITY_HP_UPDATE",//实体血量更新
    ENTITY_ENTITY_DEAD = "ENTITY_ENTITY_DEAD",//实体死亡

    // 资源加载
    RES_LOAD_FINISH = "RES_LOAD_FINISH",
}